export const COMMENT_POOL: string[] = [
  'Questo mi ha fermato lo scroll. Davvero potente.',
  'Non me lo aspettavo in questo senso. Bravo.',
  'La semplicità qui è tutto. Continua così.',
  'C\'è qualcosa di molto onesto in questo lavoro. Si sente.',
  'Ho guardato questo tre volte di fila. Grazie.',
  'Esattamente quello di cui avevo bisogno stamattina.',
  'Raro vedere qualcosa di così curato nel dettaglio.',
  'Il ritmo di questo pezzo è perfetto. Niente di troppo.',
  'Questa prospettiva non l\'avevo considerata. Mi fermo a riflettere.',
  'Semplice ma non banale. C\'è una differenza enorme.',
  'Stavo per andare avanti e poi questo mi ha bloccato. Bello.',
  'Non riesco a smettere di guardare questo. Qualcosa mi cattura.',
  'La cura che ci hai messo si vede in ogni dettaglio.',
  'Questo tipo di lavoro è raro. Apprezzo molto.',
  'Una cosa piccola che dice qualcosa di grande. Grazie.',
  'Ho mostrato questo a un amico. Ha reagito come me.',
  'Difficile fare qualcosa di così pulito. Chapeau.',
  'Mi hai fatto pensare a qualcosa che avevo dimenticato.',
  'Questo lavoro parla senza urlare. È la sua forza.',
  'Ho sempre voluto fare qualcosa del genere ma non ci sono mai riuscito. Tu sì.',
  'Ogni volta che guardo questo trovo qualcosa di nuovo.',
  'Non capita spesso di trovare qualcosa così genuino qui.',
  'L\'ho salvato. Ci torno quando ho bisogno di ispirazione.',
  'Questo è il tipo di contenuto per cui vale la pena aprire l\'app.',
  'Hai trovato qualcosa che la maggior parte delle persone ignora.',
  'La scelta dei colori qui è incredibilmente precisa.',
  'Questo suono fa qualcosa di strano alla mia testa. In senso buono.',
  'Non serve dire altro. Si capisce da solo.',
  'Ho ascoltato questo quattro volte. Non me ne stanco.',
  'Piccolo ma perfetto. Non aggiungere niente.',
  'Questo mi ha ricordato perché mi piace questo posto.',
  'La coerenza del tuo stile è qualcosa che si costruisce nel tempo.',
  'Non avrei saputo dire meglio con le parole.',
  'Questo mi ha dato energia per tutta la giornata.',
  'C\'è qualcosa di maturo in questo approccio. Si vede la crescita.',
  'Stavo cercando qualcosa del genere senza saperlo.',
  'Il tempismo è tutto, e questo è arrivato al momento giusto.',
  'Ogni elemento qui ha una ragione di esistere. Raro.',
  'Questo mi fa venir voglia di creare qualcosa anche io.',
  'Il dettaglio che hai curato di più è proprio quello che si vede di più.',
];
