export interface PostContent {
  text: string;
  tags: string[];
}

export const POST_POOL: PostContent[] = [
  { text: 'Ogni mattina è un foglio bianco. Cosa ci scrivi oggi?', tags: ['#riflessione'] },
  { text: 'Ho registrato 30 secondi di pioggia sul vetro. È più jazz di qualsiasi jazz.', tags: ['#musica', '#audio'] },
  { text: 'Il silenzio tra due note è lungo quanto vuoi.', tags: ['#musica', '#poesia'] },
  { text: 'Una foto scattata alle 4:47 del mattino. Non ricordo perché ero sveglio.', tags: ['#foto'] },
  { text: 'Il design non mente mai. Solo le persone che lo usano mentono.', tags: ['#design'] },
  { text: 'Ho finito di disegnare questa serie dopo 6 mesi. È strano lasciarla andare.', tags: ['#illustrazione', '#arte'] },
  { text: 'Niente suona come una registrazione su cassetta. Niente.', tags: ['#musica'] },
  { text: 'La luce di marzo entra diversa. Come se stesse chiedendo permesso.', tags: ['#foto', '#riflessione'] },
  { text: 'Questo loop l\'ho costruito con tre oggetti trovati in cucina.', tags: ['#musica', '#audio'] },
  { text: 'Un cortometraggio di 47 secondi. Tutto il resto era superfluo.', tags: ['#video'] },
  { text: 'La poesia non è quello che scrivi. È quello che lasci fuori.', tags: ['#poesia'] },
  { text: 'Ho fotografato 100 porte in 100 giorni. Ecco la prima.', tags: ['#foto'] },
  { text: 'Ogni colore ha un suono. Questo verde fa mi bemolle.', tags: ['#arte', '#musica'] },
  { text: 'Tre anni di sketch. Ne ho scelti dodici.', tags: ['#illustrazione'] },
  { text: 'Questo brano è nato da un errore che non ho corretto.', tags: ['#musica'] },
  { text: 'Ho filmato la stessa piazza ogni giorno per un mese. Guarda cosa cambia.', tags: ['#video', '#foto'] },
  { text: 'La creatività è una disciplina, non un talento.', tags: ['#riflessione', '#arte'] },
  { text: 'Stavo cercando un suono specifico. L\'ho trovato per caso in uno sbadiglio.', tags: ['#musica', '#audio'] },
  { text: 'Un paesaggio urbano alle 6 del mattino ha una qualità unica.', tags: ['#foto'] },
  { text: 'Ho scritto questa poesia sul treno. Il ritmo del testo segue quello dei binari.', tags: ['#poesia'] },
  { text: 'Il bianco e nero non è assenza di colore. È scelta.', tags: ['#foto', '#arte'] },
  { text: 'Questo personaggio mi ha tenuto compagnia per tre anni. Oggi lo lascio andare.', tags: ['#illustrazione'] },
  { text: 'Ci sono suoni che non ricordiamo ma che il corpo non dimentica.', tags: ['#musica', '#riflessione'] },
  { text: 'Ho montato questo video 11 volte. La dodicesima volta era quella giusta.', tags: ['#video'] },
  { text: 'Il design minimalista non è pigrizia. È coraggio.', tags: ['#design', '#riflessione'] },
  { text: 'Tutto inizia con una linea. Poi la linea decide dove andare.', tags: ['#illustrazione', '#arte'] },
  { text: 'Questa traccia è costruita su un campo di grano durante il vento.', tags: ['#musica', '#audio'] },
  { text: 'La golden hour dura 20 minuti. Non puoi perderne uno.', tags: ['#foto'] },
  { text: 'Ho riscritto questa storia 7 volte. In ognuna il protagonista cambia.', tags: ['#poesia', '#riflessione'] },
  { text: 'Cosa fai quando hai troppo da dire? Dici meno.', tags: ['#riflessione'] },
  { text: 'Un ritratto in 5 minuti. Non ho tolto nulla.', tags: ['#illustrazione', '#foto'] },
  { text: 'This city never sleeps and neither do I. #nightphotography', tags: ['#foto'] },
  { text: 'Sometimes silence is the best answer to a bad question.', tags: ['#riflessione'] },
  { text: 'Found this old melody on a tape I forgot I had.', tags: ['#musica'] },
  { text: 'Drew every face I met today. Thirty-two strangers.', tags: ['#illustrazione'] },
  { text: 'The best videos are the ones you almost didn\'t shoot.', tags: ['#video'] },
  { text: 'Ho messo la mia voce in un filtro. Non so più quale sia quella vera.', tags: ['#musica', '#audio'] },
  { text: 'L\'imperfezione è la firma di chi ha davvero fatto qualcosa.', tags: ['#riflessione', '#arte'] },
  { text: 'Ogni sfumatura di grigio racconta qualcosa che il nero e il bianco non possono.', tags: ['#foto', '#arte'] },
  { text: 'Questo pezzo l\'ho composto durante un temporale. Si sente.', tags: ['#musica'] },
  { text: 'La prospettiva cambia tutto. Cambia anche il modo in cui mi vedo.', tags: ['#foto', '#riflessione'] },
  { text: 'Un\'animazione di 8 secondi. Tre settimane di lavoro.', tags: ['#illustrazione', '#video'] },
  { text: 'Ho registrato il silenzio in sette posti diversi. Non è lo stesso silenzio.', tags: ['#audio', '#musica'] },
  { text: 'Disegnare lentamente è un atto di resistenza.', tags: ['#illustrazione', '#riflessione'] },
  { text: 'Questi colori non li ho scelti io. Si sono scelti da soli.', tags: ['#arte'] },
  { text: 'Una storia in tre immagini. Indovina la sequenza.', tags: ['#foto', '#riflessione'] },
  { text: 'Ho usato solo strumenti acustici. Nessun plugin. Nessun trucco.', tags: ['#musica'] },
  { text: 'Il video che non avrei mai voluto girare. Quello che dovevo girare.', tags: ['#video', '#riflessione'] },
  { text: 'Ogni font ha una personalità. Questa è ansiosa ma elegante.', tags: ['#design'] },
  { text: 'La nebbia di stamattina ha reso tutto uguale. E tutto uguale era bellissimo.', tags: ['#foto'] },
];
